### ISSUE TITLE
Precompiled Binaires Cx_Oracle bug

### ISSUE THREAD

**Issue by omair2084** [quentinhardy/odat#15]
There seems to be a bug in the precompiled binaries that are provided for odat.
I believe it comes from https://github.com/oracle/python-cx_Oracle/issues/49

When you use dbms_scheduler specifically, a boolean value is passed (_**auto_drop**_) and this is not properly handled by cx_Oracle, resulting in the following error message:

> Error with DBMS_SCHEDULER.create_job:ORA-03115: unsupported network datatype or representation

**Comment by omair2084** [comment]
#22

**Comment by ihebski** [comment]
# Solve cx_Oracle installation 
While trying to run the odat.py file and installing the cx_Oracle pip package ,always failed to get it installed 
checking command
  ``` python -c 'import cx_Oracle ``` <br> I got this error 
``` root@ihebski:/usr/lib/oracle/12.2/client64/lib# python -c 'import cx_Oracle' 
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named cx_Oracle
 ```
To fix this error all you have to do is to install the package with pip2.7 instead of pip ,the command as following : 
``` 
sudo pip2.7 install cx_Oracle
```
Rerun the odat file again : 
```
$python odat.py 
usage: odat.py [-h] [--version]
               {all,tnscmd,tnspoison,sidguesser,passwordguesser,utlhttp,httpuritype,utltcp,ctxsys,externaltable,dbmsxslprocessor,dbmsadvisor,utlfile,dbmsscheduler,java,passwordstealer,oradbg,dbmslob,stealremotepwds,userlikepwd,smb,privesc,cve,search,unwrapper,clean}
               ...
odat.py: error: too few arguments

```
It works now :+1:  issue solved ,happy hacking
