### ISSUE TITLE
Self Install

### ISSUE THREAD

**Issue by darryllane** [quentinhardy/odat#4]
Hi just going through your install instructions and it dawned on me. Why dont you use easy_install and setup scrip to auto install all defendants? Take a look at this for an example https://bitbucket.org/laned/dirlist/overview. Im sure you have a good reason, and Im curious to hear what it is.

**Comment by quentinhardy** [comment]
I think it's not possible to install all dependencies with ***easy_install***. For example, I don't known a method to download the Oracle dependencies while you need to download .rpm files after an authentication on their official web site. Moreover, you need to modify some configuration files on your system to install the Oracle dependencies.

I could create a bash script to automate some tasks but I think operations detailed in the readme file are not complex: It's easy to apply these operations on a Ubuntu system -:)

It's not a problem to use ***easy_install*** and ***setup*** scripts when you have python dependencies only.

I would be happy to receive any ideas or propositions in order to install more easily ODAT -:)

**Comment by darryllane** [comment]
Yes that is a fair point, I was only thing about the python dependents ;) doh!
